export const FETCH_ADMIN_PRODUCT_PENDING = "FETCH_ADMIN_PRODUCT_PENDING";
export const FETCH_ADMIN_PRODUCT_SUCCESS = "FETCH_ADMIN_PRODUCT_SUCCESS";
export const FETCH_ADMIN_PRODUCT_ERROR = "FETCH_ADMIN_PRODUCT_ERROR";

export const FETCH_ADMIN_PRODUCT_BY_ID_PENDING =
  "FETCH_ADMIN_PRODUCT_BY_ID_PENDING";
export const FETCH_ADMIN_PRODUCT_BY_ID_SUCCESS =
  "FETCH_ADMIN_PRODUCT_BY_ID_SUCCESS";
export const FETCH_ADMIN_PRODUCT_BY_ID_ERROR =
  "FETCH_ADMIN_PRODUCT_BY_ID_ERROR";

export const CREATE_ADMIN_PRODUCT_PENDING = "CREATE_ADMIN_PRODUCT_PENDING";
export const CREATE_ADMIN_PRODUCT_SUCCESS = "CREATE_ADMIN_PRODUCT_SUCCESS";
export const CREATE_ADMIN_PRODUCT_ERROR = "CREATE_ADMIN_PRODUCT_ERROR";

export const UPDATE_ADMIN_PRODUCT_PENDING = "UPDATE_ADMIN_PRODUCT_PENDING";
export const UPDATE_ADMIN_PRODUCT_SUCCESS = "UPDATE_ADMIN_PRODUCT_SUCCESS";
export const UPDATE_ADMIN_PRODUCT_ERROR = "UPDATE_ADMIN_PRODUCT_ERROR";

export const DELETE_ADMIN_PRODUCT_PENDING = "DELETE_ADMIN_PRODUCT_PENDING";
export const DELETE_ADMIN_PRODUCT_SUCCESS = "DELETE_ADMIN_PRODUCT_SUCCESS";
export const DELETE_ADMIN_PRODUCT_ERROR = "DELETE_ADMIN_PRODUCT_ERROR";

export const GET_SELECTED_IDS = "GET_SELECTED_IDS";

export const FETCH_ADMIN_PRODUCT_OPTIONS_PENDING =
  "FETCH_ADMIN_PRODUCT_OPTIONS_PENDING";
export const FETCH_ADMIN_PRODUCT_OPTIONS_SUCCESS =
  "FETCH_ADMIN_PRODUCT_OPTIONS_SUCCESS";
export const FETCH_ADMIN_PRODUCT_OPTIONS_ERROR =
  "FETCH_ADMIN_PRODUCT_OPTIONS_ERROR";
