export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCT_FILTER_OPTIONS_PENDING =
  "FETCH_PRODUCT_FILTER_OPTIONS_PENDING";
export const FETCH_PRODUCT_FILTER_OPTIONS_SUCCESS =
  "FETCH_PRODUCT_FILTER_OPTIONS_SUCCESS";
export const FETCH_PRODUCT_FILTER_OPTIONS_ERROR =
  "FETCH_PRODUCT_FILTER_OPTIONS_ERROR";

export const FETCH_PRODUCT_BY_CODE_PENDING = "FETCH_PRODUCT_BY_CODE_PENDING";
export const FETCH_PRODUCT_BY_CODE_SUCCESS = "FETCH_PRODUCT_BY_CODE_SUCCESS";
export const FETCH_PRODUCT_BY_CODE_ERROR = "FETCH_PRODUCT_BY_CODE_ERROR";

export const FETCH_RELATED_PRODUCTS_BY_CODE_PENDING = "FETCH_RELATED_PRODUCTS_BY_CODE_PENDING";
export const FETCH_RELATED_PRODUCTS_BY_CODE_SUCCESS = "FETCH_RELATED_PRODUCTS_BY_CODE_SUCCESS";
export const FETCH_RELATED_PRODUCTS_BY_CODE_ERROR = "FETCH_RELATED_PRODUCTS_BY_CODE_ERROR";

export const FETCH_PRODUCTS_WITH_FILTER_PENDING =
  "FETCH_PRODUCTS_WITH_FILTER_PENDING";
export const FETCH_PRODUCTS_WITH_FILTER_SUCCESS =
  "FETCH_PRODUCTS_WITH_FILTER_SUCCESS";
export const FETCH_PRODUCTS_WITH_FILTER_ERROR =
  "FETCH_PRODUCTS_WITH_FILTER_ERROR";

export const FETCH_PRODUCT_BY_ID_PENDING = "FETCH_PRODUCT_BY_ID_PENDING";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_ERROR = "FETCH_PRODUCT_BY_ID_ERROR";

export const FETCH_FEATURED_PRODUCT_PENDING = "FETCH_FEATURED_PRODUCT_PENDING";
export const FETCH_FEATURED_PRODUCT_SUCCESS = "FETCH_FEATURED_PRODUCT_SUCCESS";
export const FETCH_FEATURED_PRODUCT_ERROR = "FETCH_FEATURED_PRODUCT_ERROR";

export const FETCH_LATEST_PRODUCT_PENDING = "FETCH_LATEST_PRODUCT_PENDING";
export const FETCH_LATEST_PRODUCT_SUCCESS = "FETCH_LATEST_PRODUCT_SUCCESS";
export const FETCH_LATEST_PRODUCT_ERROR = "FETCH_LATEST_PRODUCT_ERROR";

export const FETCH_RELATED_PRODUCT_BY_ID_PENDING =
  "FETCH_RELATED_PRODUCT_BY_ID_PENDING";
export const FETCH_RELATED_PRODUCT_BY_ID_SUCCESS =
  "FETCH_RELATED_PRODUCT_BY_ID_SUCCESS";
export const FETCH_RELATED_PRODUCT_BY_ID_ERROR =
  "FETCH_RELATED_PRODUCT_BY_ID_ERROR";
