export const FETCH_ORDER_DASHBOARD_PENDING = "FETCH_ORDER_DASHBOARD_PENDING";
export const FETCH_ORDER_DASHBOARD_SUCCESS = "FETCH_ORDER_DASHBOARD_SUCCESS";
export const FETCH_ORDER_DASHBOARD_ERROR = "FETCH_ORDER_DASHBOARD_ERROR";
