export const FETCH_CUSTOMER_PENDING = "FETCH_CUSTOMER_PENDING";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMER_ERROR";

export const CREATE_CUSTOMER_PENDING = "CREATE_CUSTOMER_PENDING";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const UPDATE_CUSTOMER_BY_ID_PENDING = "UPDATE_CUSTOMER_BY_ID_PENDING";
export const UPDATE_CUSTOMER_BY_ID_SUCCESS = "UPDATE_CUSTOMER_BY_ID_SUCCESS";
export const UPDATE_CUSTOMER_BY_ID_ERROR = "UPDATE_CUSTOMER_BY_ID_ERROR";

export const DELETE_USER_BY_ID_PENDING = "DELETE_USER_BY_ID_PENDING";
export const DELETE_USER_BY_ID_SUCCESS = "DELETE_USER_BY_ID_SUCCESS";
export const DELETE_USER_BY_ID_ERROR = "DELETE_USER_BY_ID_ERROR";

export const GET_SELECTED_IDS = "GET_SELECTED_IDS";

export const ON_SEARCH_CUSTOMER_PENDING = "ON_SEARCH_CUSTOMER_PENDING";
export const ON_SEARCH_CUSTOMER_SUCCESS = "ON_SEARCH_CUSTOMER_SUCCESS";
export const ON_SEARCH_CUSTOMER_ERROR = "ON_SEARCH_CUSTOMER_ERROR";

export const ON_FILTER_CUSTOMER_PENDING = "ON_FILTER_CUSTOMER_PENDING";
export const ON_FILTER_CUSTOMER_SUCCESS = "ON_FILTER_CUSTOMER_SUCCESS";
export const ON_FILTER_CUSTOMER_ERROR = "ON_FILTER_CUSTOMER_ERROR";
