export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const FETCH_ORDER_BY_CODE_PENDING = "FETCH_ORDER_BY_CODE_PENDING";
export const FETCH_ORDER_BY_CODE_SUCCESS = "FETCH_ORDER_BY_CODE_SUCCESS";
export const FETCH_ORDER_BY_CODE_ERROR = "FETCH_ORDER_BY_CODE_ERROR";

export const FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_PENDING =
  "FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_PENDING";
export const FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_SUCCESS =
  "FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_SUCCESS";
export const FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_ERROR =
  "FETCH_CHECKOUT_ORDER_STATUS_BY_CODE_ERROR";

export const FETCH_ORDER_CHECKOUT_INFO_PENDING =
  "FETCH_ORDER_CHECKOUT_INFO_PENDING";
export const FETCH_ORDER_CHECKOUT_INFO_SUCCESS =
  "FETCH_ORDER_CHECKOUT_INFO_SUCCESS";
export const FETCH_ORDER_CHECKOUT_INFO_ERROR =
  "FETCH_ORDER_CHECKOUT_INFO_ERROR";

export const CREATE_ZALO_RETRY_PAYMENT_REQUEST_PENDING =
  "CREATE_ZALO_RETRY_PAYMENT_REQUEST_PENDING";
export const CREATE_ZALO_RETRY_PAYMENT_REQUEST_SUCCESS =
  "CREATE_ZALO_RETRY_PAYMENT_REQUEST_SUCCESS";
export const CREATE_ZALO_RETRY_PAYMENT_REQUEST_ERROR =
  "CREATE_ZALO_RETRY_PAYMENT_REQUEST_ERROR";

export const FETCH_USER_ORDER_HISTORY_PENDING =
  "FETCH_USER_ORDER_HISTORY_PENDING";
export const FETCH_USER_ORDER_HISTORY_SUCCESS =
  "FETCH_USER_ORDER_HISTORY_SUCCESS";
export const FETCH_USER_ORDER_HISTORY_ERROR = "FETCH_USER_ORDER_HISTORY_ERROR";

export const CREATE_ORDER_CANCELLATION_REQUEST_PENDING =
  "CREATE_ORDER_CANCELLATION_REQUEST_PENDING";
export const CREATE_ORDER_CANCELLATION_REQUEST_SUCCESS =
  "CREATE_ORDER_CANCELLATION_REQUEST_SUCCESS";
export const CREATE_ORDER_CANCELLATION_REQUEST_ERROR =
  "CREATE_ORDER_CANCELLATION_REQUEST_ERROR";

export const UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_PENDING =
  "UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_PENDING";
export const UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_SUCCESS =
  "UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_SUCCESS";
export const UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_ERROR =
  "UPDATE_ORDER_CUSTOMER_PAYMENT_METHOD_ERROR";

export const UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_PENDING =
  "UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_PENDING";
export const UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_SUCCESS =
  "UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_SUCCESS";
export const UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_ERROR =
  "UPDATE_ORDER_CUSTOMER_DELIVERY_ADDRESS_ERROR";

export const ON_BUY_ORDER_AGAIN_PENDING = "ON_BUY_ORDER_AGAIN_PENDING";
export const ON_BUY_ORDER_AGAIN_SUCCESS = "ON_BUY_ORDER_AGAIN_SUCCESS";
export const ON_BUY_ORDER_AGAIN_ERROR = "ON_BUY_ORDER_AGAIN_ERROR";
