export const CREATE_USER_SIGNUP_REQUEST_PENDING =
  "CREATE_USER_SIGNUP_REQUEST_PENDING";
export const CREATE_USER_SIGNUP_REQUEST_SUCCESS =
  "CREATE_USER_SIGNUP_REQUEST_SUCCESS";
export const CREATE_USER_SIGNUP_REQUEST_ERROR =
  "CREATE_USER_SIGNUP_REQUEST_ERROR";

export const CREATE_USER_LOGIN_REQUEST_PENDING =
  "CREATE_USER_LOGIN_REQUEST_PENDING";
export const CREATE_USER_LOGIN_REQUEST_SUCCESS =
  "CREATE_USER_LOGIN_REQUEST_SUCCESS";
export const CREATE_USER_LOGIN_REQUEST_ERROR =
  "CREATE_USER_LOGIN_REQUEST_ERROR";

export const CREATE_USER_LOGOUT_REQUEST_PENDING =
  "CREATE_USER_LOGOUT_REQUEST_PENDING";
export const CREATE_USER_LOGOUT_REQUEST_SUCCESS =
  "CREATE_USER_LOGOUT_REQUEST_SUCCESS";
export const CREATE_USER_LOGOUT_REQUEST_ERROR =
  "CREATE_USER_LOGOUT_REQUEST_ERROR";

export const CREATE_REFRESH_TOKEN_REQUEST_PENDING =
  "CREATE_REFRESH_TOKEN_REQUEST_PENDING";
export const CREATE_REFRESH_TOKEN_REQUEST_SUCCESS =
  "CREATE_REFRESH_TOKEN_REQUEST_SUCCESS";
export const CREATE_REFRESH_TOKEN_REQUEST_ERROR =
  "CREATE_REFRESH_TOKEN_REQUEST_ERROR";
