export const CREATE_PRODUCT_RATING_PENDING = "CREATE_PRODUCT_RATING_PENDING";
export const CREATE_PRODUCT_RATING_SUCCESS = "CREATE_PRODUCT_RATING_SUCCESS";
export const CREATE_PRODUCT_RATING_ERROR = "CREATE_PRODUCT_RATING_ERROR";
