export const CREATE_CART_ITEM_PENDING = "CREATE_CART_ITEM_PENDING";
export const CREATE_CART_ITEM_SUCCESS = "CREATE_CART_ITEM_SUCCESS";
export const CREATE_CART_ITEM_ERROR = "CREATE_CART_ITEM_ERROR";

export const FETCH_CART_PENDING = "FETCH_CART_PENDING";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";

export const PATCH_CART_ITEM_PENDING = "PATCH_CART_ITEM_PENDING";
export const PATCH_CART_ITEM_SUCCESS = "PATCH_CART_ITEM_SUCCESS";
export const PATCH_CART_ITEM_ERROR = "PATCH_CART_ITEM_ERROR";

export const DELETE_CART_ITEM_PENDING = "DELETE_CART_ITEM_PENDING";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_ERROR = "DELETE_CART_ITEM_ERROR";
